### ISSUE TITLE
How to on "MATERIAL" use placeholders

### ISSUE THREAD

**Issue by YTiceice** [filoghost/ChestCommands#169]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

Try to use placeholders on "MATERIAL".
But:
The icon "17" in the menu "menu/tpa.yml" has an invalid attribute "MATERIAL"

I need to make a tpa gui,and I want it don't show Offline player
My idea is %changeoutput_equals_%playerlist_online,normal,yes,17%_Offline_air_player_head%
That means if "%playerlist_online,normal,yes,17%" output is "Offline",then set MATERIAL to "air",if not set MATERIAL to "player_head"
I already know how to convert the output
But MATERIAL can't use placeholders,so please

### Chest Commands version

ChestCommands version 4.0.3

### Additional information

My idea tpa.yml:
```
17:
  MATERIAL: %changeoutput_equals_%playerlist_online,normal,yes,17%_Offline_air_player_head%
  SKULL-OWNER: '%playerlist_online,normal,yes,17%'
  POSITION-X: 8
  POSITION-Y: 2
  AMOUNT: 1
  NAME: '%playerlist_online,normal,yes,17%'
```

I provide these in the hope that you can understand my needs.
