### ISSUE TITLE
Apostrophe in give command

### ISSUE THREAD

**Issue by lynrayy** [filoghost/ChestCommands#185]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

Chestcommands can't parse menu when there is apostrophes (single quote) in /give command

```
invisible_frame:
  MATERIAL: item_frame
  POSITION-X: 1
  POSITION-Y: 3
  NAME: '&dНевидимая рамка'
  KEEP-OPEN: true
  LORE:
    - 'Свойства:'
    - '- Невидима'
    - '- Можно сломать в выживании'
    - '- Мобы и взрывы могут её сломать'
    - '- Выпадает когда на ней блок'
  ACTIONS:
    - 'console: give {player} item_frame{display:{Name:'{"text":"Невидимая нерушимая рамка","italic":false}'},EntityTag:{Silent:1b,Invulnerable:1b,Invisible:1b}}'
  NBT-DATA: '{BlockStateTag:{level:"15"}}'
```
![image](https://user-images.githubusercontent.com/59417884/204303517-005d6318-7e37-4679-987e-fb28857092ff.png)

```

[17:26:45 INFO]: [ChestCommands] Encountered 1 error(s) on load:

1) Error while initializing config file "menu\menu_creative_items.yml": invalid YAML syntax. Details:
while parsing a block collection
 in 'string', line 287, column 5:
        - 'console: give {player} item_f ...
        ^
expected <block end>, but found '{'
 in 'string', line 287, column 57:
     ... ayer} item_frame{display:{Name:'{"text":"Невидимая нерушимая рам ...
                                         ^

```

### How to reproduce

12
3'
12

### Server version

This server is running Paper version git-Paper-290 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: d98c370)

### Chest Commands version

ChestCommands version 4.0.3

### Additional information

This is works when it is just /give command. Also this give command is correct and works in game
