### ISSUE TITLE
problem with "é", "è", etc

### ISSUE THREAD

**Issue by organizatsiya** [filoghost/ChestCommands#76]
Hello, putting an accent in the description causes an error

```
PrismarinT:
  ACTIONS:
  - 'givemoney: 450'
  REQUIRED-ITEMS:
  - PRISMARINE_BRICKS, 64
  NAME: '&a&l64 blocs de prismarine taill**é**e'
  LORE:
  - '&7Prix : &a&l450$'
  MATERIAL: PRISMARINE_BRICKS
  AMOUNT: 64
  POSITION-X: 8
  POSITION-Y: 3
  KEEP-OPEN: true
```
