### ISSUE TITLE
problem with "é", "è", etc 

### ISSUE THREAD

**Issue by organizatsiya** [filoghost/ChestCommands#77]
### Description
Hello, putting an accent in the description causes an error

### How to reproduce
put an "é" in NAME: '    '

### Platform

- Server version (output of `/version`): 1.16.4
- Chest Commands version (check with `/cc`): 4.0.3

### Additional context
```
PrismarinT:
  ACTIONS:
  - 'givemoney: 450'
  REQUIRED-ITEMS:
  - PRISMARINE_BRICKS, 64
  NAME: '&a&l64 blocs de prismarine taillée'
  LORE:
  - '&7Prix : &a&l450$'
  MATERIAL: PRISMARINE_BRICKS
  AMOUNT: 64
  POSITION-X: 8
  POSITION-Y: 3
  KEEP-OPEN: true
```
